### ISSUE TITLE
the purpose of using T

### ISSUE THREAD

**Issue by ysoup-lab** [seungho-snu/SROT#1]
Hello author, what is the purpose of using T as a priori information? Isn't the value of T corresponding to the whole map the same number?

**Comment by seungho-snu** [comment]
The T map is used for the objective control parameter map.
During the training time, the value of T corresponds to the whole map with a same value. (**T** = **1** x t).
However, at inference time, the T map can be fed into the network with locally different values.
For more information, you can refer to the our FxSR paper and repository.
